set_white_noise:
  name: 设置白噪音
  description: 设置睡眠灯的白噪音
  fields:
    entity_id:
      name: 实体
      description: 要控制的灯实体
      required: true
      selector:
        entity:
          domain: light
          integration: jiachao
    noise_id:
      name: 白噪音ID
      description: 白噪音的ID（0为关闭）
      required: true
      selector:
        number:
          min: 0
          max: 100
          mode: box

set_volume:
  name: 设置音量
  description: 设置睡眠灯的音量
  fields:
    entity_id:
      name: 实体
      description: 要控制的灯实体
      required: true
      selector:
        entity:
          domain: light
          integration: jiachao
    volume:
      name: 音量
      description: 音量百分比 (0-100)
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
